<?php

namespace App\Enums;

enum NotificationType: string
{
    case EVENTO_CRIADO = 'EVENTO_CRIADO';
    case EVENTO_CANCELADO = 'EVENTO_CANCELADO';
    case INSCRICAO_CONFIRMAR = 'INSCRICAO_CONFIRMAR';
    case INSCRICAO_CANCELADA = 'INSCRICAO_CANCELADA';
    case CURSO_DISPONIVEL = 'CURSO_DISPONIVEL';
    case VAGA_ABERTA = 'VAGA_ABERTA';
    case LEMBRETE_CURSO = 'LEMBRETE_CURSO';
    case MATRICULA_CONFIRMADA = 'MATRICULA_CONFIRMADA';
    case LISTA_ESPERA_CHAMADA = 'LISTA_ESPERA_CHAMADA';
}
